import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/base.css" />
        <link rel="stylesheet" href="/css/vendor.css" />
        <link rel="stylesheet" href="/css/main.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        
        {/* Scripts loaded with Next.js Script component */}
        <Script src="/js/modernizr.js" strategy="beforeInteractive" />
        <Script src="/js/pace.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
